# Generated by Django 2.2.7 on 2020-08-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=40)),
                ('artist', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
